/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WIN 10
 */
public class Praktikum_4_2 extends javax.swing.JFrame {

    int nilai_a, nilai_b;
    boolean hasil;
    public Praktikum_4_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpertama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtkedua = new javax.swing.JTextField();
        btnsama = new javax.swing.JButton();
        btntidaksama = new javax.swing.JButton();
        btnlebih = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnlebihsama = new javax.swing.JButton();
        btnkurangsama = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txthasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROGRAM OPERATOR PEMBANDING");

        jLabel2.setText("NILAI A");

        jLabel3.setText("NILAI B");

        btnsama.setText("==");
        btnsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamaActionPerformed(evt);
            }
        });

        btntidaksama.setText("!=");
        btntidaksama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntidaksamaActionPerformed(evt);
            }
        });

        btnlebih.setText(">");
        btnlebih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihActionPerformed(evt);
            }
        });

        btnkurang.setText("<");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btnlebihsama.setText(">=");
        btnlebihsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihsamaActionPerformed(evt);
            }
        });

        btnkurangsama.setText("<=");
        btnkurangsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangsamaActionPerformed(evt);
            }
        });

        jLabel5.setText("HASIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpertama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(btnsama)
                                .addGap(18, 18, 18)
                                .addComponent(btntidaksama)
                                .addGap(18, 18, 18)
                                .addComponent(btnlebih)
                                .addGap(18, 18, 18)
                                .addComponent(btnkurang)))
                        .addGap(18, 18, 18)
                        .addComponent(btnlebihsama)
                        .addGap(18, 18, 18)
                        .addComponent(btnkurangsama)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsama)
                    .addComponent(btntidaksama)
                    .addComponent(btnlebih)
                    .addComponent(btnkurang)
                    .addComponent(btnlebihsama)
                    .addComponent(btnkurangsama))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsamaActionPerformed
       nilai_a = Integer.valueOf(txtpertama.getText());
       nilai_b = Integer.valueOf(txtkedua.getText());
        
       hasil = nilai_a == nilai_b;
       txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnsamaActionPerformed

    private void btntidaksamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntidaksamaActionPerformed
       nilai_a = Integer.valueOf(txtpertama.getText());
       nilai_b = Integer.valueOf(txtkedua.getText());
        
       hasil = nilai_a != nilai_b;
       txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btntidaksamaActionPerformed

    private void btnlebihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihActionPerformed
       nilai_a = Integer.valueOf(txtpertama.getText());
       nilai_b = Integer.valueOf(txtkedua.getText());
        
       hasil = nilai_a > nilai_b;
       txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
       nilai_a = Integer.valueOf(txtpertama.getText());
       nilai_b = Integer.valueOf(txtkedua.getText());
        
       hasil = nilai_a < nilai_b;
       txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnlebihsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihsamaActionPerformed
        nilai_a = Integer.valueOf(txtpertama.getText());
       nilai_b = Integer.valueOf(txtkedua.getText());
        
       hasil = nilai_a >= nilai_b;
       txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihsamaActionPerformed

    private void btnkurangsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangsamaActionPerformed
        nilai_a = Integer.valueOf(txtpertama.getText());
       nilai_b = Integer.valueOf(txtkedua.getText());
        
       hasil = nilai_a <= nilai_b;
       txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangsamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum_4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum_4_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnkurangsama;
    private javax.swing.JButton btnlebih;
    private javax.swing.JButton btnlebihsama;
    private javax.swing.JButton btnsama;
    private javax.swing.JButton btntidaksama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtkedua;
    private javax.swing.JTextField txtpertama;
    // End of variables declaration//GEN-END:variables
}
